version: "3"

volumes:
    db-data:
        external: false

services:
    web:
        build: lumen/
        ports:
            - "8000:80"
        volumes:
            - ./lumen:/app 
        depends_on:
            - db

    front:
        build: front/
        volumes:
            - ./front:/front
        ports:
            - "80:3000"
        depends_on:
            - web

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db-data:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080 
