version: "3"

volumes:
    db-data:
        external: false

services:
    php:
        build: lumen/
        ports:
            - 9000:9000
        volumes:
            - ./lumen:/app

    nginx:
        image: nginx
        volumes:
            - ./lumen:/app
            - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
        ports:
            - 8000:80
        links:
            - php
        depends_on:
            - db

    front:
        build: front/
        volumes:
            - ./front:/front
        ports:
            - "80:3000"
        depends_on:
            - nginx

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db-data:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080 
